spring:
  profiles:
    active: @profileActive@
logging:
  level:
    # root日志以WARN级别输出
    root: info
    # 此包下所有class以DEBUG级别输出
    com.kiritor.hshop: debug
  project:
    application: hshop

swagger:
  enable: true